name: 🔍 Checks

on:
  push:
    branches: [main]
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  check:
    runs-on: ubuntu-latest
    name: 📝 Check build
    permissions:
      contents: read
    steps:
      - name: 📦 Checkout Repository
        uses: actions/checkout@v4

      - name: 🏗️ Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: 🛠️ Install dependencies
        run: npm ci

      - name: 🔬 Lint checks
        run: npm run lint

      - name: 🔍 Type checks
        run: npm run check

      - name: 🔨 Compile checks
        run: npm run build

  test:
    runs-on: ubuntu-latest
    needs: check
    name: 🎭 Playwright tests
    permissions:
      contents: read
    steps:
      - name: 📦 Checkout Repository
        uses: actions/checkout@v4

      - name: 🏗️ Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: 🛠️ Install dependencies
        run: npm ci

      - name: 🛠️ Install Playwright browsers
        run: npx playwright install --with-deps

      - name: 🎭 Run Playwright tests
        run: npm run test

      - name: 🚚 Upload test report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 14
